version: '3'

services:
  manifold:
    build: .
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8000}:8000'
    env_file: .env
    environment:
      - APP_PORT=8000

networks:
  ns-stream:
    external: true
